import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Lay from "./comp/Lay"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (

    <html lang="en">
      <body>
        <Lay>
          {children}
        </Lay>
      </body >
    </html >

  );
}
